ALTER TABLE users
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS taluk TEXT,
ADD COLUMN IF NOT EXISTS district TEXT;

ALTER TABLE service_providers
ADD COLUMN IF NOT EXISTS district TEXT;

ALTER TABLE permit_applications
ADD COLUMN IF NOT EXISTS district TEXT;