ALTER TABLE permit_applications
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS taluk TEXT;

ALTER TABLE service_providers
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS taluk TEXT;